[package]
name = "zkbitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.5"
bitcoin = { version = "0.31.0", features = [
    "serde",
], git = "https://github.com/mimoo/rust-bitcoin/", branch = "mimoo/fix_0_31" }
bitcoincore-rpc = "0.18"
clap = { version = "4.4.10", features = ["derive"] }
env_logger = "0.10.1"
hex = "0.4.3"
itertools = "0.12.0"
jsonrpc = "0.16"
rand = "0.8.5"
reqwest = "0.11"
secp256k1 = "0.28.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sha3 = "0.10.8"
tempdir = "0.3.7"
tokio = { version = "1.34", features = ["macros"] }

[patch.crates-io]
# see docs/serialization.md on why we do this
bitcoin = { git = "https://github.com/mimoo/rust-bitcoin/", branch = "mimoo/fix_0_31" }
