[package]
name = "zkbitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.31.0"
jsonrpsee = { version = "0.20", features = ["client"] }
tokio = "1.34"
